In [85]:
import torch
x=torch.rand(5,3)
print(x)

tensor([[0.1013, 0.9210, 0.8042],
        [0.4420, 0.1865, 0.2049],
        [0.5451, 0.7458, 0.3245],
        [0.7901, 0.6071, 0.9116],
        [0.6055, 0.6524, 0.4136]])


In [87]:
from __future__ import print_function
import torch
x=torch.empty(5,3) #构造一个5x3的矩阵，不进行初始化操作
print(x)
x=torch.rand(5,3) #构造一个随机初始化矩阵
print(x)
x=torch.zeros(5,3,dtype=torch.long) #构造一个矩阵为全0，而且数据类型是long
print(x)
x=torch.tensor([5.5,3]) # 构造一个张量，直接使用数据 
print(x)

tensor([[-3.8791e-26,  1.6129e-42,  1.4013e-45],
        [ 0.0000e+00,  1.4013e-45,  0.0000e+00],
        [ 1.4013e-45,  0.0000e+00,  1.4013e-45],
        [ 0.0000e+00,  1.4013e-45,  0.0000e+00],
        [ 1.4013e-45,  0.0000e+00,  1.4013e-45]])
tensor([[0.3811, 0.3787, 0.6217],
        [0.7125, 0.2496, 0.3180],
        [0.0522, 0.2475, 0.8153],
        [0.9972, 0.5068, 0.0738],
        [0.9327, 0.8820, 0.8912]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])
